### ISSUE TITLE
Версия плагина в Chrome webstore

### ISSUE THREAD

**Issue by TheQmaks** [APIdogRU/APIdogPlusExtension#7]
Вы бы обновили в вебсторе хрома плагин до версии 3.0, а то сейчас только через ручную загрузку подгрузить можно.
![image](https://user-images.githubusercontent.com/11361354/45991149-39a6fe80-c08c-11e8-9e6b-321969bbb0ec.png)

**Comment by vladislav805** [comment]
Косяк в том, что загружали расширение не мы, а Лавр. А Лавр пропал.

**Comment by TheQmaks** [comment]
Так создайте другой)

**Comment by vladislav805** [comment]
Нет аккаунта разработчика ¯\_(ツ)_/¯
А создавать свой и платить только ради полумертвого проекта - не, спасибо...

**Comment by TheQmaks** [comment]
Ну да, аргумент. А что с проектом не так? Впадлу развивать дальше?

**Comment by vladislav805** [comment]
VK скатился. Везде реклама, везде урезание API, лишь бы официальными приложениями с рекламой использовались. + От той аудитории, что была, когда был офлайн - осталось около 1/4 и постепенно падает. Остались лишь те, кто токены подменял, и то, половина из них тоже слилась после исправления дыры.
Лично я переехал в Telegram, пса поддерживаю чисто чтоб был.

**Comment by TheQmaks** [comment]
Может просто нехватает фишек. Лично мне на доге не нравится диз, он прям отбивает желание залипать там. Потом куча всяких неисправностей непонятных. А насчет токенов - почему просто не сделать отдельную версию по подписке для получения прибыли?)

**Comment by vladislav805** [comment]
Ну, как минимум из-за того, что эта "версия" тогда бы тоже выпускалась под нашим именем. А мы не хотим быть хозяевами сервиса для взломщиков и нечестных людей. Во-первых, я сам против этого; во-вторых, таким образом у нас еще репутация падает в глазах администрации ВК (которая, может быть, когда-нибудь сняла бы блок и все юзеры перестали бы думать, что именно мы (пес) ломаем аккаунты; так ведь в предупреждении написано при переходе, "вк хуйни не скажет" же!).

**Comment by TheQmaks** [comment]
Ну, с другой стороны да выходит так.
